# Generated by Django 4.0.7 on 2023-11-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_baseuser_birth_date_baseuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalAssistant',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('educational_assistant_number', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'EducationalAssistant',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='ITManager',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('itmanager_number', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ITManager',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('professor_number', models.CharField(max_length=10, unique=True)),
                ('major', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Professor',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_number', models.CharField(max_length=10, unique=True)),
                ('intrance_year', models.DateField(auto_now_add=True)),
                ('years', models.PositiveIntegerField(default=0)),
                ('militery_service_status', models.CharField(choices=[('exempt', 'Exempt'), ('cardservice', 'CardService'), ('educationalexempt', 'EducationalExempt')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
            bases=('users.baseuser',),
        ),
    ]
