# Generated by Django 4.0.7 on 2023-11-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
        ('account', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_students', to='term.coursestudent'),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='intrance_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term.term'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='educationalassistant',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='educationalassistant',
            name='major',
            field=models.ManyToManyField(to='faculty.major'),
        ),
    ]
