# Generated by Django 4.0.7 on 2023-11-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.professor'),
        ),
    ]
