# Generated by Django 4.0.7 on 2023-11-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_student_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='intrance_term',
            new_name='entrance_term',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='intrance_year',
            new_name='entrance_year',
        ),
    ]
