# Generated by Django 4.0.7 on 2023-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_intrance_term_student_entrance_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='entrance_term',
            field=models.CharField(max_length=255),
        ),
    ]
