# Generated by Django 4.0.7 on 2023-11-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_approvedcourse_created_at_approvedcourse_updated_at_and_more'),
        ('account', '0007_remove_student_courses_alter_student_entrance_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.major'),
        ),
    ]
