# Generated by Django 4.0.7 on 2023-11-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_student_courses_alter_student_entrance_term'),
        ('faculty', '0002_approvedcourse_created_at_approvedcourse_updated_at_and_more'),
        ('term', '0002_coursestudent_created_at_coursestudent_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termcourse',
            old_name='name',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='term',
            name='professor_registered',
        ),
        migrations.RemoveField(
            model_name='term',
            name='students_registered',
        ),
        migrations.RemoveField(
            model_name='term',
            name='term_courses',
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='termcourse',
            unique_together={('course', 'term')},
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='term_taken',
        ),
    ]
