# Generated by Django 4.0.7 on 2023-11-20 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_rename_name_termcourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='emergency_deletion_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 20, 15, 21, 55, 292260), null=True),
        ),
    ]
