# Generated by Django 4.0.7 on 2023-11-20 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0004_term_emergency_deletion_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='emergency_deletion_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
